//! Measure the natural bounding box of each problem component and emit
//! a baseline toml file + per-fixture PNG.
//!
//! Renders each fixture in an auto-sized typst page (`#set page(width:
//! auto, height: auto, margin: 0pt)`) and reads the compiled Document's
//! first-page dimensions — which equal the content's bbox exactly.
//! Prints a table of (fixture → width_cm, height_cm) and writes
//! `crates/core/generated/cell-sizes.toml` with both the raw measured
//! sizes and "declared" sizes (measurement ceiled to the next 0.1cm
//! for layout breathing room). Also writes a tight-cropped PNG per
//! fixture under `out/components/` for visual review.
//!
//! The toml is the source of truth for the refactor's
//! `WorksheetType::cell_size_cm(max_digits)`. Re-run after any
//! component change; diff the output.
//!
//! Usage:
//!   cargo run --release --example measure_cells -p pencil-ready-core

use std::path::PathBuf;

use anyhow::{Context, Result};
use pencil_ready_core::{Fonts, OutputFormat, compile_typst, measure_typst};

#[path = "common/fixtures.rs"]
mod fixtures;
use fixtures::{FIXTURES, ceil_mm, padded, preamble};

fn build_source(snippet: &str) -> String {
    format!(
        "{preamble}\n#set page(width: auto, height: auto, margin: 0pt)\n#set text(font: body-font, size: 10pt)\n\n#{padded}\n",
        preamble = preamble(),
        padded = padded(snippet),
    )
}

// A4 content area after standard margins. Used ONLY to print the
// diagnostic `cols_a4` / `rows_a4` columns below; does NOT feed the
// emitted toml. Shared with the rest of the pipeline via
// `pencil_ready_core::content_area_cm(Paper::A4)`.
fn a4_content_cm() -> (f32, f32) {
    // Use the worst-case chrome height (all three header sections) so
    // the diagnostic columns reflect the most-constrained body area.
    pencil_ready_core::content_area_cm(
        pencil_ready_core::Paper::A4,
        pencil_ready_core::HEADER_HEIGHT_CM,
    )
}

struct Row {
    id: &'static str,
    label: &'static str,
    measured_w: f32,
    measured_h: f32,
    declared_w: f32,
    declared_h: f32,
    cols_a4: u32,
    rows_a4: u32,
}

fn main() -> Result<()> {
    let root = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|p| p.parent())
        .expect("no repo root")
        .to_path_buf();

    let fonts = Fonts::load(&root)?;

    let png_dir = root.join("out/components");
    std::fs::create_dir_all(&png_dir)?;

    let (a4_w, a4_h) = a4_content_cm();
    let mut rows: Vec<Row> = Vec::with_capacity(FIXTURES.len());
    for f in FIXTURES {
        let src = build_source(f.snippet);
        let (mw, mh) = measure_typst(&src, &root, &fonts)
            .with_context(|| format!("measuring fixture {}", f.id))?;
        let (dw, dh) = (ceil_mm(mw), ceil_mm(mh));
        let cols_a4 = (a4_w / dw).floor() as u32;
        let rows_a4 = (a4_h / dh).floor() as u32;

        // Tight-cropped PNG of the component — "isolated component
        // rendering" from LAYOUT_REFACTOR.md. Same source as the
        // measurement; auto-sized page gives a pixel-perfect cell image.
        let png = compile_typst(&src, OutputFormat::Png, &root, &fonts)
            .with_context(|| format!("rendering fixture {}", f.id))?;
        std::fs::write(png_dir.join(format!("{}.png", f.id)), png)?;

        rows.push(Row {
            id: f.id, label: f.label,
            measured_w: mw, measured_h: mh,
            declared_w: dw, declared_h: dh,
            cols_a4, rows_a4,
        });
    }

    // --- Printed table ---
    println!();
    println!("A4 portrait content area: {:.2} cm wide × {:.2} cm tall",
             a4_w, a4_h);
    println!();
    println!("{:<28} {:>7} {:>7}   {:>7} {:>7}   {:>4} {:>4}",
             "id", "meas w", "meas h", "decl w", "decl h", "cols", "rows");
    println!("{}", "-".repeat(80));
    for r in &rows {
        println!("{:<28} {:>7.2} {:>7.2}   {:>7.1} {:>7.1}   {:>4} {:>4}",
                 r.id, r.measured_w, r.measured_h,
                 r.declared_w, r.declared_h, r.cols_a4, r.rows_a4);
    }

    // --- Write toml ---
    let out_path = root.join("crates/core/generated/cell-sizes.toml");
    std::fs::create_dir_all(out_path.parent().unwrap())?;
    let toml = render_toml(&rows);
    std::fs::write(&out_path, toml)?;
    println!();
    println!("wrote {}", out_path.display());
    println!("wrote {} PNGs under {}", rows.len(), png_dir.display());

    Ok(())
}

fn render_toml(rows: &[Row]) -> String {
    let mut s = String::new();
    s.push_str(
        "# Auto-generated by `cargo run --example measure_cells -p pencil-ready-core`.\n\
         # Do not edit by hand — re-run the tool instead.\n\
         #\n\
         # `measured_*_cm` is the raw bbox from typst. `width_cm` / `height_cm`\n\
         # are the measured values ceiled to the next 0.1cm, giving layout\n\
         # a small safety margin. Downstream (cell_size_cm in the refactor)\n\
         # should use the declared `width_cm` / `height_cm`.\n\n\
         schema_version = 1\n\n",
    );
    for r in rows {
        s.push_str("[[cell]]\n");
        s.push_str(&format!("id = {:?}\n", r.id));
        s.push_str(&format!("label = {:?}\n", r.label));
        s.push_str(&format!("width_cm = {:.1}\n", r.declared_w));
        s.push_str(&format!("height_cm = {:.1}\n", r.declared_h));
        s.push_str(&format!("measured_width_cm = {:.3}\n", r.measured_w));
        s.push_str(&format!("measured_height_cm = {:.3}\n", r.measured_h));
        s.push('\n');
    }
    s
}
