//! Two-step linear equation worksheet — `ax + b = c`, solve for `x`.
//!
//! Answers are always non-negative integers because the problems are
//! generated by picking `x` first and computing `c = a*x + b`.
//!
//! Problem representation as `Vec<u32>`: `[a, b, x, c, form]` where
//!   form = 0 → canonical plus       `ax + b = c`
//!   form = 1 → const-first plus     `b + ax = c`
//!   form = 2 → canonical minus      `ax - b = c` (only when a*x ≥ b)

use crate::template;
use crate::{WorksheetParams, WorksheetType};

pub fn generate_typ(params: &WorksheetParams) -> anyhow::Result<String> {
    let problems = generate_problems(params);
    let (implicit, variable) = match &params.worksheet {
        WorksheetType::AlgebraTwoStep {
            implicit,
            variable,
            ..
        } => (*implicit, variable.as_str()),
        _ => unreachable!(),
    };
    // Algebra uses `·` regardless of locale — `×` looks too much like the
    // variable `x` once variables are introduced. Matches the US pre-algebra
    // convention (elementary `×` → pre-algebra `·` → algebra implicit).
    // The explicit --symbol flag still overrides this.
    let symbol = "sym.dot.op";
    template::render_algebra_two_step(symbol, &problems, params, implicit, variable)
}

fn generate_problems(params: &WorksheetParams) -> Vec<Vec<u32>> {
    let (a_range, b_range, x_range, mix_forms) = match &params.worksheet {
        WorksheetType::AlgebraTwoStep {
            a_range,
            b_range,
            x_range,
            mix_forms,
            ..
        } => (*a_range, *b_range, *x_range, *mix_forms),
        _ => unreachable!(),
    };

    use rand::rngs::SmallRng;
    use rand::seq::SliceRandom;
    use rand::{Rng, SeedableRng};

    let mut rng = match params.seed {
        Some(s) => SmallRng::seed_from_u64(s),
        None => SmallRng::from_entropy(),
    };

    // Enumerate every (a, b, x) triple. Answers are always clean integers
    // by construction. One entry per combination — the form is randomized
    // at generation time when mix_forms is on.
    //
    // Form 2 (subtraction) is only valid when a*x >= b so that c >= 0.
    let mut all: Vec<(u32, u32, u32, u32, u32)> = Vec::new();
    for a in a_range.min..=a_range.max {
        for b in b_range.min..=b_range.max {
            for x in x_range.min..=x_range.max {
                let form = if mix_forms {
                    // Candidate forms for this triple. Form 2 joins only
                    // when the subtraction produces a non-negative c.
                    let mut valid = vec![0u32, 1];
                    if a * x >= b {
                        valid.push(2);
                    }
                    valid[rng.gen_range(0..valid.len())]
                } else {
                    0
                };
                let c = if form == 2 { a * x - b } else { a * x + b };
                all.push((a, b, x, c, form));
            }
        }
    }

    all.shuffle(&mut rng);
    let total = params.total_problems() as usize;
    if total > 0 && all.len() > total {
        all.truncate(total);
    }

    all.into_iter()
        .map(|(a, b, x, c, form)| vec![a, b, x, c, form])
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::DigitRange;

    #[test]
    fn test_answer_always_integer() {
        let params = test_params(
            DigitRange::new(2, 12),
            DigitRange::new(1, 30),
            DigitRange::new(0, 20),
            true,
        );
        let problems = generate_problems(&params);
        assert!(!problems.is_empty());
        for p in &problems {
            let (a, b, x, c, form) = (p[0], p[1], p[2], p[3], p[4]);
            match form {
                2 => assert_eq!(a * x - b, c, "form=2 invariant: a*x - b == c"),
                _ => assert_eq!(a * x + b, c, "form=0/1 invariant: a*x + b == c"),
            }
        }
    }

    #[test]
    fn test_subtraction_form_never_negative() {
        // Force a setup where subtraction would often go negative if
        // unchecked (small a, small x, large b).
        let params = test_params(
            DigitRange::new(2, 3),
            DigitRange::new(20, 30),
            DigitRange::new(0, 5),
            true,
        );
        let problems = generate_problems(&params);
        for p in &problems {
            let (a, b, x, form) = (p[0], p[1], p[2], p[4]);
            if form == 2 {
                assert!(a * x >= b, "form=2 emitted with a*x < b: {a}*{x} < {b}");
            }
        }
    }

    #[test]
    fn test_mix_forms_off_gives_canonical() {
        let params = test_params(
            DigitRange::new(2, 5),
            DigitRange::new(1, 10),
            DigitRange::new(0, 10),
            false,
        );
        let problems = generate_problems(&params);
        for p in &problems {
            assert_eq!(p[4], 0, "mix_forms=false should yield only form=0");
        }
    }

    #[test]
    fn test_includes_x_zero_and_one() {
        // With x_range 0-5, we should see x=0 and x=1 in the enumerated set.
        let params = test_params(
            DigitRange::new(2, 2),
            DigitRange::new(1, 1),
            DigitRange::new(0, 5),
            false,
        );
        let problems = generate_problems(&params);
        let xs: Vec<u32> = problems.iter().map(|p| p[2]).collect();
        assert!(xs.contains(&0), "x=0 should appear");
        assert!(xs.contains(&1), "x=1 should appear");
    }

    #[test]
    fn test_ranges_respected() {
        let a = DigitRange::new(3, 5);
        let b = DigitRange::new(2, 8);
        let x = DigitRange::new(0, 10);
        let params = test_params(a, b, x, true);
        let problems = generate_problems(&params);
        for p in &problems {
            assert!(p[0] >= a.min && p[0] <= a.max);
            assert!(p[1] >= b.min && p[1] <= b.max);
            assert!(p[2] >= x.min && p[2] <= x.max);
        }
    }

    fn test_params(
        a_range: DigitRange,
        b_range: DigitRange,
        x_range: DigitRange,
        mix_forms: bool,
    ) -> WorksheetParams {
        WorksheetParams {
            worksheet: WorksheetType::AlgebraTwoStep {
                a_range,
                b_range,
                x_range,
                variable: "x".into(),
                implicit: false,
                mix_forms,
            },
            num_problems: 12,
            cols: 3,
            paper: "a4".into(),
            debug: false,
            seed: Some(42),
            symbol: None,
            locale: Default::default(),
            pages: 1,
            solve_first: false,
            include_answers: false,
        }
    }
}
